spring:
  devtools:
    restart:
      exclude:  public/**
      enabled:  true
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    cache: false
  rabbitmq:
      port: 5672
      host: localhost
      username: springcloud
      password: 123456

server:
  port: 8080
